package org.cdb.filesystem.exception;

public class ExceptionMessage
{
    public static final String UNEXPECTED_ERROR = "An unexpected error occurred.";
    public static final String ENTITY_SAVED_SUCCESSFULLY = "entity saved successfully";
    public static final String ENTITY_UPDATED_SUCCESSFULLY = "entity updated successfully";
    public static final String ENTITY_DELETED_SUCCESSFULLY = "entity deleted successfully";
    public static final String MISSING_REQUIRED = "missing required fields";
    public static final String FILE_NOT_FOUND = "File not found";

    public static final String ERROR_MESSAGE = "error";
    public static final String SUCCESS_MESSAGE = "success";
    public static final String WARNING_MESSAGE = "warning";


    //    public static final String USER_NOT_FOUND = "Sorry, we couldn't find the user you're looking for. Please double-check the entered information and try again.";
    public static final String EXPIRED_TOKEN = "invalid token";
    public static final String INVALID_TOKEN = "Invalid token";
    public static final String INVALID_CREDENTIALS = "Invalid credentials";
    public static final String ACCESS_DENIED = "Sorry, you do not have permissions to access this resource.";
    public static final String NOT_AUTHENTICATION = "no authentication credentials found";
}
